### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by VisionR1** [aviraxp/Zygisk-KeystoreInjection#2]
Why A14+ only ?
Can't this make it for A11+ ?

**Comment by aviraxp** [comment]
I think it will work for A11+, I just didn't test it.

**Comment by VisionR1** [comment]
> I think it will work for A11+, I just didn't test it.

Oh good to know, I just ask because say install failed need A14+ when go to install via Magisk.

**Comment by aviraxp** [comment]
Have you tried it?

**Comment by VisionR1** [comment]
> Have you tried it?

Yeah.
I have change in the customize.sh the API 34 to 30 to install it, but still say BL is unlocked.

**Comment by aviraxp** [comment]
Do you add a keybox.xml in /data/adb？

**Comment by VisionR1** [comment]
> Do you add a keybox.xml in /data/adb？

Oh yeah, how forgot about this? 😂🤣
I try with the sw keybox and yeah say BL is locked.
I don't know about pass.
So if this works on A11, why not downgrade from API 34 to 30 ?

**Comment by aviraxp** [comment]
Thx, will add.

**Comment by VisionR1** [comment]
> Thx, will add.

Thank you for this create module.
One last can you make a release? 
Unfortunately most users, still not know how complile with Android Studio.

**Comment by aviraxp** [comment]
This project has ci: https://github.com/aviraxp/Zygisk-KeystoreInjection/actions/runs/9819989767/job/27114084642

**Comment by VisionR1** [comment]
> This project has ci: https://github.com/aviraxp/Zygisk-KeystoreInjection/actions/runs/9819989767/job/27114084642

Good to know.
Thanks.
