### ISSUE TITLE
Question 2

### ISSUE THREAD

**Issue by VisionR1** [aviraxp/Zygisk-KeystoreInjection#3]
Hi, this work only for local attestation?
Because one user on XDA, try it and say this
![IMG_20240713_112024](https://github.com/user-attachments/assets/7a51231e-6d9b-46e5-b072-82225b01dc83)
![IMG_20240713_111752](https://github.com/user-attachments/assets/ee431ff5-534b-4f3f-be45-3d72e6fb6327)

**Comment by aviraxp** [comment]
It can defeat remote attestation in theory. The ussue is that this modules doesn't implement or regenerate enough strings apart from rootOfTrust.
