### ISSUE TITLE
how to download Zygisk-KeystoreInjection module ? where to get the module file ?

### ISSUE THREAD

**Issue by floean** [aviraxp/Zygisk-KeystoreInjection#4]
how to download Zygisk-KeystoreInjection module ? where to get the module file ?

**Comment by VisionR1** [comment]
Here you can found project ci: https://github.com/aviraxp/Zygisk-KeystoreInjection/actions/runs/9819989767/job/27114084642

**Comment by floean** [comment]
and where can I find the installation instructions?

**Comment by floean** [comment]
![изображение](https://github.com/user-attachments/assets/ce0e5ebc-69d6-4d75-9953-5cc1a16dfbdb)
![изображение](https://github.com/user-attachments/assets/cee94569-1d4b-490a-8de2-d51066e93525)
What did I do wrong? I installed the module and for some reason it doesn't work

**Comment by aviraxp** [comment]
Read the code and provide a keybox.
